$file = "c:\Users\USEER\Documents\LEXIS\client\src\components\documents\document-modals.tsx"
$content = Get-Content -Encoding UTF8 $file

# Apply replacements one by one
$content = $content -replace "Ξ•Ο€ΞµΞΎΞµΟΞ³Ξ±ΟƒΞ―Ξ± Ξ•Ξ³Ξ³ΟΞ¬Ο†ΞΏΟ…", "Επεξεργασία Εγγράφου"
$content = $content -replace "Ξ£Ο„ΞΏΞΉΟ‡ΞµΞ―Ξ± Ξ ΟΟ‰Ο„ΞΏΞΊΟΞ»Ξ»ΞΏΟ…", "Στοιχεία Πρωτοκόλλου"
$content = $content -replace "Ξ'ΟΞΉΞΈΞΌΟΟ‚ Ξ ΟΟ‰Ο„ΞΏΞΊΟΞ»Ξ»ΞΏΟ…", "Αριθμός Πρωτοκόλλου"
$content = $content -replace "Ξ—ΞΌΞµΟΞΏΞΌΞ·Ξ½Ξ―Ξ± Ξ ΟΟ‰Ο„ΞΏΞΊΟΞ»Ξ»ΞΏΟ…", "Ημερομηνία Πρωτοκόλλου"
$content = $content -replace "Ξ£Ο„ΞΏΞΉΟ‡ΞµΞ―Ξ± ΞΟΞ³ΞΏΟ…", "Στοιχεία Έργου"
$content = $content -replace "ID ΞΟΞ³ΞΏΟ… \(ΞΞ'853\)", "ID Έργου (ΝΑ853)"
$content = $content -replace "Ξ¤ΟΟ€ΞΏΟ‚ Ξ"Ξ±Ο€Ξ¬Ξ½Ξ·Ο‚", "Τύπος Δαπάνης"
$content = $content -replace "Ξ"ΞΉΞΊΞ±ΞΉΞΏΟΟ‡ΞΏΞΉ", "Δικαιούχοι"
$content = $content -replace "Ξ ΟΞΏΟƒΞΈΞ®ΞΊΞ· Ξ­Ο‰Ο‚ 10 Ξ΄ΞΉΞΊΞ±ΞΉΞΏΟΟ‡Ο‰Ξ½", "Προσθήκη έως 10 δικαιούχων"
$content = $content -replace "Ξ ΟΞΏΟƒΞΈΞ®ΞΊΞ· Ξ"ΞΉΞΊΞ±ΞΉΞΏΟΟ‡ΞΏΟ…", "Προσθήκη Δικαιούχου"
$content = $content -replace "ΞΞ½ΞΏΞΌΞ±", "Όνομα"
$content = $content -replace "Ξ•Ο€ΟΞ½Ο…ΞΌΞΏ", "Επίθετο"
$content = $content -replace "Ξ Ξ±Ο„ΟΟΞ½Ο…ΞΌΞΏ", "Πατρώνυμο"
$content = $content -replace "Ξ'Ξ¦Ξ"", "ΑΦΜ"
$content = $content -replace "Ξ ΞΏΟƒΟ", "Ποσό"
$content = $content -replace "Ξ"ΟΟƒΞ·", "Δόση"
$content = $content -replace "Ξ£Ο…Ξ½ΞΏΞ»ΞΉΞΊΟ Ξ ΞΏΟƒΟ:", "Συνολικό Ποσό:"
$content = $content -replace "Ξ'Ο€ΞΏΞΈΞ®ΞΊΞµΟ…ΟƒΞ·\.\.\.", "Αποθήκευση..."
$content = $content -replace "Ξ'Ο€ΞΏΞΈΞ®ΞΊΞµΟ…ΟƒΞ· Ξ'Ξ»Ξ»Ξ±Ξ³ΟΞ½", "Αποθήκευση Αλλαγών"
$content = $content -replace "Ξ"ΞΉΞ±Ξ³ΟΞ±Ο†Ξ® Ξ•Ξ³Ξ³ΟΞ¬Ο†ΞΏΟ…", "Διαγραφή Εγγράφου"
$content = $content -replace "Ξ•Ξ―ΟƒΟ„Ξµ Ξ²Ξ­Ξ²Ξ±ΞΉΞΏΞΉ ΟΟ„ΞΉ ΞΈΞ­Ξ»ΞµΟ„Ξµ Ξ½Ξ± Ξ΄ΞΉΞ±Ξ³ΟΞ¬ΟΞµΟ„Ξµ Ξ±Ο…Ο„Ο Ο„ΞΏ Ξ­Ξ³Ξ³ΟΞ±Ο†ΞΏ; Ξ'Ο…Ο„Ξ® Ξ· ΞµΞ½Ξ­ΟΞ³ΞµΞΉΞ± Ξ΄ΞµΞ½ ΞΌΟ€ΞΏΟΞµΞ― Ξ½Ξ± Ξ±Ξ½Ξ±ΞΉΟΞµΞΈΞµΞ―\.", "Είστε βέβαιοι ότι θέλετε να διαγράψετε αυτό το έγγραφο; Αυτή η ενέργεια δεν μπορεί να αναιρεθεί."
$content = $content -replace "Ξ"ΞΉΞ±Ξ³ΟΞ±Ο†Ξ®\.\.\.", "Διαγραφή..."
$content = $content -replace "Ξ"ΞΉΞ±Ξ³ΟΞ±Ο†Ξ®", "Διαγραφή"
$content = $content -replace "Ξ•ΞΎΞ±Ξ³Ο‰Ξ³Ξ® Ξ•Ξ³Ξ³ΟΞ¬Ο†Ο‰Ξ½", "Εξαγωγή Εγγράφων"
$content = $content -replace "Ξ•Ο€ΞµΞΎΞµΟΞ³Ξ±ΟƒΞ―Ξ±\.\.\.", "Επεξεργασία..."
$content = $content -replace "Ξ›Ξ®ΟΞ·", "Λήψη"
$content = $content -replace "Ξ'ΞΊΟΟΟ‰ΟƒΞ·", "Ακύρωση"

Set-Content -Encoding UTF8 $file $content
Write-Host "File fixed successfully!"
