// ... (rest of the file, assuming it contains the necessary imports and other code) ...

// Assuming this is part of a larger function or query builder
.from('users')
      .select('id, email, name, role, unit, active')
// ... (rest of the query builder code) ...

// ... (rest of the file) ...